### ISSUE TITLE
ilk yorum 🥇 

### ISSUE THREAD

**Issue by firatpayalan** [mertozler/Trendyol-example#1]
kafka da bir mesaj produce etmeye başladığın anda kafka broker ı eğer üzerinde o topic hiç yoksa otomatik bir şekilde üretmeye başlar. bu sayede sen de producer olarak mesaj göndermeye hazır olursun. 

log-writer-microservice de aslında consumer la ilgli bir kod parçası gördüm, burası sadece mesaj produce edecekse 

`cluster, err := sarama.NewConsumer(brokerAddrs, config)`

bunun hiçbir şekilde log-writer-microservice içerisinde olmamalı. çünkü bu kod parçasını girdiğin anda consumer ayağa kaldırıyorsun. ama bu micro bir producer yapan microservice.

```goland
func CreateTopic(kafkaConn string, topic string) {
	brokerAddrs := []string{kafkaConn}
	config := sarama.NewConfig()
	config.Version = sarama.V2_1_0_0
	admin, err := sarama.NewClusterAdmin(brokerAddrs, config)
	if err != nil {
		log.Fatal("Error while creating cluster admin: ", err.Error())
	}
	defer func() { _ = admin.Close() }()
	cluster, err := sarama.NewConsumer(brokerAddrs, config)
	if err != nil {
		panic(err)
	}
	topics, _ := cluster.Topics()
	if slices.Contains(topics, topic) {
		fmt.Println("Topic is already existing")
	} else {
		err = admin.CreateTopic(topic, &sarama.TopicDetail{
			NumPartitions:     1,
			ReplicationFactor: 1,
		}, false)
		if err != nil {
			log.Fatal("Error while creating topic: ", err.Error())

		}
	}
}

```

kafka broker ı başlattıktan sonra yukarıdaki configurasyonu girmene şimdilik gerek yok. burada programatik bir şekilde topic oluşturuyorsun. şu aşamada kafka_producer.go ile gönderdiğin mesajı consumer ile yakaladığında bence ilk aşamada güzel bir yol kat etmiş olacağız ❤️ 

ek olarak sana bir docker-compose.yml dosyası göndereceğim. linkedin de gönderdiğim makaleleri okuduktan sonra local inde kafka ayağa kaldırmak için sadece bunu çalıştırman yeterli olacak. 

```yml
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
```

bunu docker-compose.yml şeklinde kayıt edip, aşağıdaki komutu uyguladığın vakit doğrudan bir kafka broker ı docker ile çalıştıracaktır. 

`docker-compose up -d`
